[project]
name = "marine-debris"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10.16"
dependencies = [
    "pandas>=2.2.3",
    "scikit-image>=0.25.0",
    "streamlit>=1.41.1",
    "ultralytics>=8.3.53",
]
